#!/usr/bin/env python3
"""
=========================================================
SDE Portfolio Intelligence V4

Tool      : create_file.py
Version   : 1.0.0
Purpose   : Create project files safely.

Author    : SDE Framework
=========================================================
"""

from pathlib import Path
from datetime import datetime
import argparse
import sys


HEADER = """\
=========================================================
FILE AUTO-GENERATED

Generated By : create_file.py
Generated On : {timestamp}

=========================================================

"""


def create_file(file_path: str, overwrite: bool = False):

    path = Path(file_path)

    # Create parent folders if required
    path.parent.mkdir(parents=True, exist_ok=True)

    if path.exists() and not overwrite:
        print(f"[EXISTS ] {path}")
        return

    content = HEADER.format(
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    )

    path.write_text(content, encoding="utf-8")

    print(f"[CREATED] {path}")


def main():

    parser = argparse.ArgumentParser(
        description="Create project files."
    )

    parser.add_argument(
        "file",
        help="File path to create"
    )

    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing file"
    )

    args = parser.parse_args()

    create_file(
        args.file,
        args.overwrite
    )


if __name__ == "__main__":
    main()